name: BaeHyeonWooPL
version: 1.5
main: com.github.qogusdn1017.baehyeonwoopl.Main
api-version: '1.15'
depend: [Kotlin, Tap]
authors: [BaeHyeonWoo, HappyAndJust, B1ackAnge1]

commands:
  activestatus:
    description: "Check that Plugin Status is Activated!"
  credits:
    description: "Credits of this Plugin Creation."
  gm:
    description: "Change Player's Gamemodes. Reference of Essentials."
  stop:
    description: "Stop command only for Operators."
  compass:
    description: "Gives you compass with just one commandline."
  diasetpvp:
    description: "Diamond Armor + Diamond Sword"
  chainsetpvp:
    description: "Chain Armor + Stone Sword"
  goldsetpvp:
    description: "Golden Armor + Golden Sword"
  ironsetpvp:
    description: "Iron Armor + Iron Sword"
  leathersetpvp:
    description: "Leather Armor + Wooden Sword"
  god:
    description: "Gives User Great Buffs."
  invisible:
    description: "Reference of Essentials. Gives Player invisibility."
  ev:
    description: "Reference of Essentials. Gives Player invisibility."
  rmgod:
    description: "Removes buff effects."
  rmev:
    description: "Removes Invisibility."
  rminvisi:
    description: "Removes Invisibility."
  spacemode:
    description: "Spacemode for fun."
  deactspace:
    description: "Deactivate Spacemode."
  giveop:
    description: "Give you Administrative Permission."
  feed:
    description: "Satisfition of Hunger."
  heal:
    description: "Heals user."
  difficulty:
    description: "Change Game Difficulty."
  gamemode:
    description: "Change Player's Gamemodes. Reference of Essentials."
  ci:
    description: "Clear Player's Inventory. Reference of Essentials"
  nightvision:
    description: "Gives User Night Vision."